### ISSUE TITLE
CUDA Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by CalKK8** [LeelaChessZero/lc0#1409]
**DESCRIPTION**

Error message: `Unhandled exception in worker thread: CUDA error: no kernel image is available for execution on the device (../../src/neural/cuda/common_kernels.cu:254)`

**HARDWARE + SOFTWARE**
Engine Binary: Lc0 v0.26.1
GPU: NVIDIA Tesla K80

Already tried attaching parameter `--backend-opts=custom_winograd=false`, but still doesn't work.

**FULL LOG**
```
$ ./lc0
       _
|   _ | |
|_ |_ |_| v0.26.1 built Aug 12 2020
Found configuration file: ./lc0.config
go nodes 100
Found pb network file: ./384x30-t60-4300.pb.gz
Creating backend [cudnn-auto]...
Switching to [cudnn]...
CUDA Runtime version: 11.0.0
Cudnn version: 8.0.2
Latest version of CUDA supported by the driver: 11.0.0
GPU: Tesla K80
GPU memory: 11.173 Gb
GPU clock frequency: 875.5 MHz
GPU compute capability: 3.7
Unhandled exception in worker thread: CUDA error: no kernel image is available for execution on the device (../../src/neural/cuda/common_kernels.cu:254) 
Aborted (core dumped)
```

**Comment by borg323** [comment]
This is probably due to the deprecation of CC 37 gpus (among others) in cuda 11.  You can either revert to cuda 10 or try the following (untested and not portable to other gpus).
In `meson.build` find the line `files += cuda_gen.process(cuda_files_nvcc_common)` and change it to `files += cuda_gen.process(cuda_files_nvcc_common, extra_args: ['-arch=compute_37', '-code=sm_37'])`

**Comment by Ratipoka** [comment]
I had the same issue, I manage to build successfuly with what @borg323 recomanded build has been unable to use lc0 in scid. It seems to work when I run it with the windows powershell : when I type uci, I get the expected thing.

**Comment by Ratipoka** [comment]
I can now confirm that it worked fine for me. Thank you so much @borg323 for your help !

**Comment by borg323** [comment]
For future reference: we have a better way now, just add the `-Dcc_cuda=37` option to the build, like `./build.sh -Dcc_cuda=37` and any other options you use. Or if you have a CC 5.0 card use `-Dcc_cuda=50` instead.

**Comment by Naphthalin** [comment]
@borg323 can this be archived?

**Comment by borg323** [comment]
Closing, people searching for this will find it either way.
