### ISSUE TITLE
Unspecified Launch Failure CUDA 11.1

### ISSUE THREAD

**Issue by RRVyper** [LeelaChessZero/lc0#1461]
Using v0.26.3 on Alienware M17 R2 with RTX 2080 (Max Q version) causes the following random errors:

Using cuda-fp16:
Unhandled exception in worker thread: CUDA error: unspecified launch failure (C:\Users\rrvyp\source\lc0-0.26.3\src\neural\cuda\network_cuda.cc:569)

Using cudnn-fp16:
Unhandled exception in worker thread: CUDA error: unspecified launch failure (C:\Users\rrvyp\source\lc0-0.26.3\src\neural\cuda\network_cudnn.cc:788)

This occurred when running a 10 game tournament in Arena using 256x20-t40-1541.pb.gz weights file with lc0 compiled with CUDA 11.1 and cuDNN 8.05 and nvidia driver 457.30. Note that these compiles were specifically for compute_75/sm_75.

It also randomly crashes using the precompiled downloads. I also compiled using CUDA 10.2 and cuDNN 7 (with appropriate nvidia drivers) and still had the same errors. Sometimes it will cause a BSOD bugcheck in Win 10, other times nvlddmkm recovers but shows many errors in event viewer. I also tested in Manjaro linux (I dual boot) and it crashed there as well.

Thinking it was a hardware issue, I ran many CUDA benchmarks (Phoronix Test Suite, Compubench 2.0, and demo samples in the CUDA folder) but did not see any issues.

I ran v0.26.2 and v0.23.0 (both downloaded pre-compiled versions) and also had no issues (I used cudnn-fp-16). Similarly, Fat Fritz does not cause the errors.

I'm summarizing what I wrote in Discord as this is a better forum for keeping issues separated.

Randy

**Comment by RRVyper** [comment]
It appears that it is only the cudnn-fp16 and cuda-fp16 backends in v0.26.3 that cause lc0 to randomly crash for me. I just finished a 20 game tournament, using all the same parameters as before, without issue.

Randy

**Comment by ankan-ban** [comment]
not sure what is causing these random errors. 
To isolate if this is due to the new path added in v0.26.3, can you please run with --backend-opts=res_block_fusing=false ?

**Comment by RRVyper** [comment]
I tested cuda-fp16 using --backend-opts=res_block_fusing=false and the crash happened just 14 moves into the game. This time there were no nvlddmkm errors in the Event Viewer, just the lc0.exe crash:

Faulting application name: lc0.exe, version: 0.0.0.0, time stamp: 0x5f82117a
Faulting module name: lc0.exe, version: 0.0.0.0, time stamp: 0x5f82117a
Exception code: 0xc0000409
Fault offset: 0x000000000006b44d
Faulting process id: 0x2144
Faulting application start time: 0x01d6be79ad17aa08
Faulting application path: D:\Arena\Engines\lc0-v0.26.3CUDA\lc0.exe
Faulting module path: D:\Arena\Engines\lc0-v0.26.3CUDA\lc0.exe
Report Id: 04a15bb1-7698-4425-a1a8-b5d09502b912
Faulting package full name: 
Faulting package-relative application ID: 

There was also a crash of GameBar(?), but I suspect it's probably because Windows locked up for about 60 seconds:

Faulting application name: GameBar.exe, version: 5.420.10222.0, time stamp: 0x5f9194c3
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xc0000409
Fault offset: 0x000000000010b65c
Faulting process id: 0x35d8
Faulting application start time: 0x01d6be7959a79a43
Faulting application path: C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_5.420.10222.0_x64__8wekyb3d8bbwe\GameBar.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 2fb0cc0e-ec90-41e9-bcbf-3872e6b8817b
Faulting package full name: Microsoft.XboxGamingOverlay_5.420.10222.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

Randy

**Comment by ankan-ban** [comment]
Apart from that new path (res_block_fusing), I don't think anything changed that would result in CUDA related crashes.

I would have suspected some hardware overheating/stability issue as the errors are somewhat random and happens after some time, but you already tested other benchmarks that run without issues. Still for testing can you try under-clocking your GPU (e.g: reduce core/memory clocks by 100-200Mhz using third party tools like MSI afterburner/evga precision), and see if it fixes the problem?

**Comment by RRVyper** [comment]
Thanks, Ankan. That's a good suggestion. I thought it was hardware related but could not get it to fail using other means. There are different overclocking profiles available on the Alienware laptop. Perhaps the default setting is just too close to the edge. I will do some experimenting and report back what I find. I really want to be able to use the full potential of lc0 and my hardware.

Randy

**Comment by mega-optimus** [comment]
I'm working on a cuda project without using cudnn, the same "unspecified launch failure" happens to cuda 10.2/11.1 + sm_75 combination, while cuda 10.2 + sm_61 works fine.

**Comment by RRVyper** [comment]
That's interesting @mega-optimus. Unfortunately, the precompiled 0.26.3 versions were also failing for me. But I think I am making some progress. My laptop uses Alienware Command Center to handle overclocking, etc. I removed all the Alienware software, but still had the crash. I then reinstalled AWCC and tried using it to lower the GPU clock, leaving the CPU auto-managed. It still failed. On reboot, AWCC notified me that due to an error (it ended in BSOD that time), it was disabling the overclocking (CPU). I decided to run a tournament between lc0 v0.26.2 (cudnn-fp16) and v0.26.3 (CUDA-fp16) and no crash!? I then decided to go back to lc0 v0.26.3 CUDA against SF12 NNUE, which always failed, and it has been running without a crash through game 5 (about 35 mins.). Perhaps it is a CPU issue in my case. I was always testing against SF12. The CPU temp gets to 100 °C momentarily (known issue with the i9-9980HK in the Alienware m17 r2). Maybe it's SF12 that's indirectly causing lc0 to crash?? I'll need to do some more testing. I'm pretty sure I tried a different engine opponent a few days ago.

Randy

**Comment by RRVyper** [comment]
Well, after running through 10 games without an issue, I rebooted, checked that overclocking was still disabled, and began a 30 game tournament against SF12 NNUE. Unfortunately it crashed in the first game:
Unhandled exception in worker thread: CUDA error: the launch timed out and was terminated (C:\Users\...\source\lc0-0.26.3\src\neural\cuda\network_cuda.cc:569)
with many nvlddmkm errors in event viewer (no BSOD this time).
For lc0:
Faulting application name: lc0.exe, version: 0.0.0.0, time stamp: 0x5fb02d2b
Faulting module name: lc0.exe, version: 0.0.0.0, time stamp: 0x5fb02d2b
Exception code: 0xc0000409
Fault offset: 0x00000000000ead6d
Faulting process id: 0x3ee4
Faulting application start time: 0x01d6bfa8fb78b574
Faulting application path: D:\Arena\Engines\RR_lc0\lc0.exe
Faulting module path: D:\Arena\Engines\RR_lc0\lc0.exe
Report Id: 0bd3b3a8-d6dd-4002-af61-2ecbbca95753
Faulting package full name: 
Faulting package-relative application ID: 

Not sure where to go now...

Randy

**Comment by RRVyper** [comment]
Decided to re-run another tournament overclocked, using v0.26.2 against SF12 NNUE, expecting it to pass - no joy, it failed. So, I'm thinking it's not lc0. No exception in the log but event viewer did show appcrash for lc0:

Faulting application name: lc0.exe, version: 0.0.0.0, time stamp: 0x5f4f96e0
Faulting module name: ntdll.dll, version: 10.0.19041.610, time stamp: 0xe5d7ed5c
Exception code: 0xc0000374
Fault offset: 0x00000000000fed29
Faulting process id: 0xe8c
Faulting application start time: 0x01d6bfae171ba8ed
Faulting application path: D:\Arena\Engines\lc0v0.26.2\lc0.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: aa305040-9233-48aa-9b1d-00c4de2b0762
Faulting package full name: 
Faulting package-relative application ID: 

But no nvlddmkm entries. Now re-running lc0 v0.26.3 cuda-fp16 against v0.26.2 cudnn-fp16, overclocked. Don't expect it to fail. Now thinking it's related to running against SF12 NNUE, or SF12 itself?

<sigh>

Randy

**Comment by RRVyper** [comment]
Well, I was wrong. Laptop just rebooted by itself in the middle of game 3. Guess it's CPU related...

Randy

**Comment by RRVyper** [comment]
I ran a 30 game tournament of lc0 v0.26.3 cuda-fp16 against v0.26.2 cudnn-fp16 with overclocking disabled and it completed, but lc0 v0.26.3 CUDA against SF12 NNUE failed again with overclocking disabled. I think it's time to take lc0 out of the equation and run SF against itself.

Randy

**Comment by RRVyper** [comment]
Just finished a 30 game tournament of SF12 NNUE (avx2) against SF12 NNUE (bmi2) overclock disabled, and a 20 game tournament overclocked (same SF12 engines) and had no issues. Doesn't look like an issue with the CPU.

Randy

**Comment by RRVyper** [comment]
Started tournament of lc0 v0.23.0 against SF12, overclocked. Crash right at the end of game 3. Started another tournament using Fritz between pre-compiled v0.26.3 and SF12, BSOD bugcheck in first game. Frustrating. Seems fp16 is the only thing common.

Randy

**Comment by RRVyper** [comment]
Now 20 game tournament lc0 v0.26.3 cudnn-fp16 vs lc0 cudnn-fp16 crashed during game 11. So, yes, even against itself. Maybe it's time to give up...

Randy

**Comment by RRVyper** [comment]
I updated CUDA (to cuda_11.1.1_456.81_win10) and installed the latest Alienware video driver (456.87) for this laptop but lc0 is still crashing. I then used cudnn-fp16 to analyze a game in Arena (so that it was the only engine loaded) and it crashed many times. It seems to always be BEX64 in the event viewer:

Fault bucket 1842349292240363114, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: lc0.exe
P2: 0.0.0.0
P3: 5fb02d2b
P4: lc0.exe
P5: 0.0.0.0
P6: 5fb02d2b
P7: 00000000000ead6d
P8: c0000409
P9: 0000000000000007
P10: 

One thing I noticed is that there are many (435 to be exact) warnings when compiling lc0 (cudnn) myself. Not sure if it's related:

[msbuild.log](https://github.com/LeelaChessZero/lc0/files/5584743/msbuild.log)

Randy

**Comment by RRVyper** [comment]
Just to add what I see in Manjaro when running lc0 v0.26.3 (cuda-fp16) which crashes fairly quickly in a cutechess tournament vs Oki-Maguro-12-R1- journalctl shows many repeating lines of these 3 entries:

```
Nov 23 18:30:17 RR-M17R2 kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=1493, Graphics SM Warp Exception on (GPC 0, TPC 0, SM 0): Illegal Instruction Encoding
Nov 23 18:30:17 RR-M17R2 kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=1493, Graphics SM Global Exception on (GPC 0, TPC 0, SM 0): Multiple Warp Errors
Nov 23 18:30:17 RR-M17R2 kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=1493, Graphics Exception: ESR 0x504730=0x10009 0x504734=0x4 0x504728=0x4c1eb72 0x50472c=0x174
```

(probably similar to the nvlddmkm event viewer entries in Windows 10)

...followed a few lines later by the core dump:

```
Nov 23 18:30:21 RR-M17R2 systemd-coredump[5130]: Process 3941 (lc0) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 5127:
                                                 #0  0x00007f3200640615 raise (libc.so.6 + 0x3d615)
                                                 #1  0x00007f3200629862 abort (libc.so.6 + 0x26862)
                                                 #2  0x00005632c5b62544 n/a (/home/.../.local/bin/lc0 + 0x5f544)
```

I ran [cuda-memtest](https://github.com/ComputationalRadiationPhysics/cuda_memtest), [gpu-burn](https://github.com/wilicc/gpu-burn) and [cublasgemm-benchmark](https://github.com/hma02/cublasgemm-benchmark) in linux without any errors. I don't think it's hardware.

Maybe lc0 just doesn't like the RTX 2080 Max Q versions??

Randy

**Comment by RRVyper** [comment]
> Still for testing can you try under-clocking your GPU (e.g: reduce core/memory clocks by 100-200Mhz using third party tools like MSI afterburner/evga precision), and see if it fixes the problem?

I think I have found the issue, thanks to your suggestion @ankan-ban. I had tried using Alienware Command Center to lower the clock speeds of the GPU, but it turns out it just moves everything back to 'Overclocking Off'. I needed to go further. I installed MSI Afterburner and lowered the RTX 2080 Max-Q base clock by 100 MHz (although nvidia's GPU Boost 4.0 still will exceed the lower Boost setting). That seems to have solved the issue. I have run a few 20 game tournaments now using v0.26.3 against SF12 and lc0 has not crashed. There are other things I can try, like switching to performance mode instead of balanced, but things then start getting loud. I hope I can find a setting that allows me to not have to underclock the GPU. I'm not sure how much performance is lost, but I'll benchmark lc0 to find out.

Randy

P.S. Feel free to close this issue.

**Comment by borg323** [comment]
@RRVyper feel free to reopen if you get more crashes.

**Comment by RRVyper** [comment]
@borg323 @ankan-ban 

I just want to follow up that I had the system board (which also contains the RTX 2080 GPU) replaced in my Alienware m17 r2 and that has fixed the issue with lc0 crashing randomly. It's worth noting that every benchmark program, stress tool or Dell diagnostic software passed with no errors even with hours of runtime. Some of the software (in Linux) included [Deep Learning Benchmark Tools](https://technopremium.com/) which can test fp16 or fp32 operations. Also, another tool called [gpu-burn](https://github.com/wilicc/gpu-burn) which tests CUDA cores and [cuda-memtest](https://github.com/ComputationalRadiationPhysics/cuda_memtest) which tests the memory did not find any problems.

So thanks to the devs here for the lc0 program. It put some heat and light on an issue that other software was unable to reveal.

Randy
