### ISSUE TITLE
cudnn-fp16 gives "illegal memory access" in v0.31-rc1 -- worked fine on v0.30

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#2007]
_Originally posted by @fsmosca in https://github.com/LeelaChessZero/lc0/discussions/2000#discussioncomment-8952889_

What is wrong?

```
uciok
isready
readyok
ucinewgame
Found pb network file: F:\Chess\Engines\Lc0\lc0-v0.31.0-rc1-windows-gpu-nvidia-cudnn/791556.pb.gz
Creating backend [cudnn-auto]...
Switching to [cudnn-fp16]...
CUDA Runtime version: 10.0.0
Cudnn version: 7.4.2
Latest version of CUDA supported by the driver: 12.2.0
GPU: NVIDIA GeForce GTX 1650 SUPER
GPU memory: 3.99957 GiB
GPU clock frequency: 1770 MHz
GPU compute capability: 7.5
isready
readyok
ucinewgame
isready
readyok
position startpos
go movetime 60000
Unhandled exception in worker thread: CUDA error: an illegal memory access was encountered (c:\projects\lc0\src\neural\cuda\network_cudnn.cc:865)
```

**Comment by borg323** [comment]
Replying here as well. Since it was confirmed it works with v0.30.0, [here](https://ci.appveyor.com/api/buildjobs/xpg6y3c063prploq/artifacts/build%2Flc0.exe) is a version with only the backend (and anything required) changes on top of it.

**Comment by borg323** [comment]
@fsmosca can you try the following two tests:
1. Run with net [744204](https://training.lczero.org/get_network?sha=0f2f738e314bf618384045d4320a55333375d273d093adb805a4268ee53b519c) instead of 791556
2. Run with `--backend-options=min_batch=1`

**Comment by fsmosca** [comment]
### lc0-v0.31.0-rc1

```
PS F:\Chess\Engines\Lc0\lc0-v0.31.0-rc1-windows-gpu-nvidia-cudnn> ./lc0.exe
       _
|   _ | |
|_ |_ |_| v0.31.0-rc1 built Mar 25 2024
uci
id name Lc0 v0.31.0-rc1

uciok
isready
readyok
ucinewgame
Found pb network file: F:\Chess\Engines\Lc0\lc0-v0.31.0-rc1-windows-gpu-nvidia-cudnn/0f2f738e314bf618384045d4320a55333375d273d093adb805a4268ee53b519c
Creating backend [cudnn-auto]...
Switching to [cudnn-fp16]...
CUDA Runtime version: 10.0.0
Cudnn version: 7.4.2
Latest version of CUDA supported by the driver: 12.2.0
GPU: NVIDIA GeForce GTX 1650 SUPER
GPU memory: 3.99957 GiB
GPU clock frequency: 1770 MHz
GPU compute capability: 7.5
setoption name backendoptions value min_batch=1
isready
readyok
go movetime 5000
Found pb network file: F:\Chess\Engines\Lc0\lc0-v0.31.0-rc1-windows-gpu-nvidia-cudnn/0f2f738e314bf618384045d4320a55333375d273d093adb805a4268ee53b519c
Creating backend [cudnn-auto]...
Switching to [cudnn-fp16]...
CUDA Runtime version: 10.0.0
Cudnn version: 7.4.2
Latest version of CUDA supported by the driver: 12.2.0
GPU: NVIDIA GeForce GTX 1650 SUPER
GPU memory: 3.99957 GiB
GPU clock frequency: 1770 MHz
GPU compute capability: 7.5
Unhandled exception in worker thread: CUBLAS error: CUBLAS_STATUS_ALLOC_FAILED (c:\projects\lc0\src\neural\cuda\inputs_outputs.h:80)
PS F:\Chess\Engines\Lc0\lc0-v0.31.0-rc1-windows-gpu-nvidia-cudnn>
```

### lc0-v0.31.0-rc2

**Comment by borg323** [comment]
Thanks. No need to run multiple tests, just rc1 is fine.

**Comment by borg323** [comment]
Does <https://ci.appveyor.com/api/buildjobs/xqa206wmbqvdp3vw/artifacts/build%2Flc0.exe> work?

**Comment by borg323** [comment]
Another test to do is to try whether the `cuda-fp16` backend works with the same lc0.exe.

**Comment by fsmosca** [comment]
> Does https://ci.appveyor.com/api/buildjobs/xqa206wmbqvdp3vw/artifacts/build%2Flc0.exe work?

That one did not crash.

```
PS F:\Chess\Engines\Lc0\lc0-v0.31.0-rc1-windows-gpu-nvidia-cudnn> ./lc0-2
       _
|   _ | |
|_ |_ |_| v0.31.0-dev+git.16f04df built Apr 10 2024
```

**Comment by borg323** [comment]
Here is another version to test: <https://ci.appveyor.com/api/buildjobs/cqw425tfr712xamk/artifacts/build%2Flc0.exe>
In case you are wondering, I'm trying to bisect the changes in the backend to find the one responsible, and we are getting there.

**Comment by fsmosca** [comment]
> Here is another version to test: https://ci.appveyor.com/api/buildjobs/cqw425tfr712xamk/artifacts/build%2Flc0.exe In case you are wondering, I'm trying to bisect the changes in the backend to find the one responsible, and we are getting there.

Did not crash.

```
       _
|   _ | |
|_ |_ |_| v0.31.0-dev+git.b41f722 built Apr 13 2024
uci
id name Lc0 v0.31.0-dev+git.b41f722
```

**Comment by borg323** [comment]
Thanks again. This effectively pinpoints the problematic commit, but unfortunately it is a large one so it will take time to analyze. In the meantime, maybe <https://ci.appveyor.com/api/buildjobs/ri3noodk8sa15tur/artifacts/build%2Flc0.exe> from #2015 helps, it is lc0 master but built using different options.

**Comment by fsmosca** [comment]
> Thanks again. This effectively pinpoints the problematic commit, but unfortunately it is a large one so it will take time to analyze. In the meantime, maybe https://ci.appveyor.com/api/buildjobs/ri3noodk8sa15tur/artifacts/build%2Flc0.exe from #2015 helps, it is lc0 master but built using different options.

Failed

```
PS F:\Chess\Engines\Lc0\lc0-v0.31.0-rc1-windows-gpu-nvidia-cudnn> ./lc0-4
       _
|   _ | |
|_ |_ |_| v0.32.0-dev+git.f42c674 built Apr 13 2024
uci
id name Lc0 v0.32.0-dev+git.f42c674

'''

uciok
isready
readyok
ucinewgame
Found pb network file: F:\Chess\Engines\Lc0\lc0-v0.31.0-rc1-windows-gpu-nvidia-cudnn/791556.pb.gz
Creating backend [cudnn-auto]...
Switching to [cudnn-fp16]...
CUDA Runtime version: 10.0.0
Cudnn version: 7.4.2
Latest version of CUDA supported by the driver: 12.2.0
GPU: NVIDIA GeForce GTX 1650 SUPER
GPU memory: 3.99957 GiB
GPU clock frequency: 1770 MHz
GPU compute capability: 7.5
setoption name Backend value cudnn-fp16
isready
readyok
ucinewgame
Found pb network file: F:\Chess\Engines\Lc0\lc0-v0.31.0-rc1-windows-gpu-nvidia-cudnn/791556.pb.gz
Creating backend [cudnn-fp16]...
CUDA Runtime version: 10.0.0
Cudnn version: 7.4.2
Latest version of CUDA supported by the driver: 12.2.0
GPU: NVIDIA GeForce GTX 1650 SUPER
GPU memory: 3.99957 GiB
GPU clock frequency: 1770 MHz
GPU compute capability: 7.5
go movetime 60000
Unhandled exception in worker thread: CUDA error: an illegal memory access was encountered (c:\projects\lc0\src\neural\cuda\network_cudnn.cc:865)

```

**Comment by borg323** [comment]
Final test to help us focus further investigations, is this last lc0 version also failing with the `cuda-fp16` backend?

**Comment by fsmosca** [comment]
> Final test to help us focus further investigations, is this last lc0 version also failing with the `cuda-fp16` backend?

It did not crash.

```
setoption name Backend value cuda-fp16
```

**Comment by borg323** [comment]
Thanks, this is better news than I hoped, limits the search considerably.

**Comment by borg323** [comment]
Thanks again for patiently helping with all those tests. The last one was very helpful and I have a fix in #2016. Please test <https://ci.appveyor.com/api/buildjobs/o4ti8c56m56ie6na/artifacts/build%2Flc0.exe> to confirm there are no other issues.

**Comment by borg323** [comment]
The fix is now merged in master. Please test if it works: <https://ci.appveyor.com/api/buildjobs/ygxcfw5g7rys9fgo/artifacts/build%2Flc0.exe>

**Comment by fsmosca** [comment]
> The fix is now merged in master. Please test if it works: https://ci.appveyor.com/api/buildjobs/ygxcfw5g7rys9fgo/artifacts/build%2Flc0.exe

It now works on cudnn-fp16.

**Comment by borg323** [comment]
Thank you, this is now fixed.
